-- Buns & Patties real menu. Run after schema.sql.
delete from rewards; delete from order_lines; delete from menu_items; delete from categories;

insert into categories (id, name, sort) values
  ('burgers','Smash Burgers',1),
  ('wings','Wings',2),
  ('fries','Fries',3),
  ('beverages','Beverages',4);

insert into menu_items (id, category_id, name, description, price, featured, available, sort, modifier_groups) values
  ('og','burgers','The OG','Ketchup, mustard, sliced onion, pickles, American cheese',9,true,true,1,'[{"id": "patty", "name": "Patties", "required": true, "min": 1, "max": 1, "options": [{"id": "p_single", "name": "Single patty", "priceDelta": 0}, {"id": "p_double", "name": "Double patty", "priceDelta": 2}, {"id": "p_triple", "name": "Triple patty", "priceDelta": 4}]}, {"id": "toppings_add", "name": "Add toppings", "required": false, "min": 0, "max": 9, "options": [{"id": "t_lettuce", "name": "Lettuce", "priceDelta": 0}, {"id": "t_pickles", "name": "Pickles", "priceDelta": 0}, {"id": "t_tomatoes", "name": "Tomatoes", "priceDelta": 0}, {"id": "t_cucumbers", "name": "Cucumbers", "priceDelta": 0}, {"id": "t_onions", "name": "Sliced onions", "priceDelta": 0}, {"id": "t_jalapenos", "name": "Jalapeños", "priceDelta": 0}, {"id": "t_egg", "name": "Fried egg", "priceDelta": 1.5}, {"id": "t_avocado", "name": "Avocado", "priceDelta": 1.5}, {"id": "t_bacon", "name": "Beef bacon", "priceDelta": 1.5}]}, {"id": "sauces_add", "name": "Add sauces", "required": false, "min": 0, "max": 6, "options": [{"id": "s_ketchup", "name": "Ketchup", "priceDelta": 0}, {"id": "s_mustard", "name": "Mustard", "priceDelta": 0}, {"id": "s_mayo", "name": "Mayo", "priceDelta": 0}, {"id": "s_og", "name": "OG House", "priceDelta": 0}, {"id": "s_jranch", "name": "Jalapeño Ranch", "priceDelta": 0}, {"id": "s_bbq", "name": "BBQ", "priceDelta": 0}]}, {"id": "rm_og", "name": "Remove", "required": false, "min": 0, "max": 5, "options": [{"id": "r_og_ketchup", "name": "No ketchup", "priceDelta": 0}, {"id": "r_og_mustard", "name": "No mustard", "priceDelta": 0}, {"id": "r_og_onion", "name": "No sliced onion", "priceDelta": 0}, {"id": "r_og_pickles", "name": "No pickles", "priceDelta": 0}, {"id": "r_og_cheese", "name": "No American cheese", "priceDelta": 0}]}]'),
  ('wake_n_smash','burgers','Wake N Smash','OG sauce, lettuce, pickles, tomatoes, cucumber, avocado, American cheese',10,true,true,2,'[{"id": "patty", "name": "Patties", "required": true, "min": 1, "max": 1, "options": [{"id": "p_single", "name": "Single patty", "priceDelta": 0}, {"id": "p_double", "name": "Double patty", "priceDelta": 2}, {"id": "p_triple", "name": "Triple patty", "priceDelta": 4}]}, {"id": "toppings_add", "name": "Add toppings", "required": false, "min": 0, "max": 9, "options": [{"id": "t_lettuce", "name": "Lettuce", "priceDelta": 0}, {"id": "t_pickles", "name": "Pickles", "priceDelta": 0}, {"id": "t_tomatoes", "name": "Tomatoes", "priceDelta": 0}, {"id": "t_cucumbers", "name": "Cucumbers", "priceDelta": 0}, {"id": "t_onions", "name": "Sliced onions", "priceDelta": 0}, {"id": "t_jalapenos", "name": "Jalapeños", "priceDelta": 0}, {"id": "t_egg", "name": "Fried egg", "priceDelta": 1.5}, {"id": "t_avocado", "name": "Avocado", "priceDelta": 1.5}, {"id": "t_bacon", "name": "Beef bacon", "priceDelta": 1.5}]}, {"id": "sauces_add", "name": "Add sauces", "required": false, "min": 0, "max": 6, "options": [{"id": "s_ketchup", "name": "Ketchup", "priceDelta": 0}, {"id": "s_mustard", "name": "Mustard", "priceDelta": 0}, {"id": "s_mayo", "name": "Mayo", "priceDelta": 0}, {"id": "s_og", "name": "OG House", "priceDelta": 0}, {"id": "s_jranch", "name": "Jalapeño Ranch", "priceDelta": 0}, {"id": "s_bbq", "name": "BBQ", "priceDelta": 0}]}, {"id": "rm_wake", "name": "Remove", "required": false, "min": 0, "max": 7, "options": [{"id": "r_wk_og", "name": "No OG sauce", "priceDelta": 0}, {"id": "r_wk_lettuce", "name": "No lettuce", "priceDelta": 0}, {"id": "r_wk_pickles", "name": "No pickles", "priceDelta": 0}, {"id": "r_wk_tomatoes", "name": "No tomatoes", "priceDelta": 0}, {"id": "r_wk_cucumber", "name": "No cucumber", "priceDelta": 0}, {"id": "r_wk_avocado", "name": "No avocado", "priceDelta": 0}, {"id": "r_wk_cheese", "name": "No American cheese", "priceDelta": 0}]}]'),
  ('lone_star_heat','burgers','Lone Star Heat 🌶','Jalapeño ranch sauce, lettuce, sliced onions, jalapeños, American cheese',9,true,true,3,'[{"id": "patty", "name": "Patties", "required": true, "min": 1, "max": 1, "options": [{"id": "p_single", "name": "Single patty", "priceDelta": 0}, {"id": "p_double", "name": "Double patty", "priceDelta": 2}, {"id": "p_triple", "name": "Triple patty", "priceDelta": 4}]}, {"id": "toppings_add", "name": "Add toppings", "required": false, "min": 0, "max": 9, "options": [{"id": "t_lettuce", "name": "Lettuce", "priceDelta": 0}, {"id": "t_pickles", "name": "Pickles", "priceDelta": 0}, {"id": "t_tomatoes", "name": "Tomatoes", "priceDelta": 0}, {"id": "t_cucumbers", "name": "Cucumbers", "priceDelta": 0}, {"id": "t_onions", "name": "Sliced onions", "priceDelta": 0}, {"id": "t_jalapenos", "name": "Jalapeños", "priceDelta": 0}, {"id": "t_egg", "name": "Fried egg", "priceDelta": 1.5}, {"id": "t_avocado", "name": "Avocado", "priceDelta": 1.5}, {"id": "t_bacon", "name": "Beef bacon", "priceDelta": 1.5}]}, {"id": "sauces_add", "name": "Add sauces", "required": false, "min": 0, "max": 6, "options": [{"id": "s_ketchup", "name": "Ketchup", "priceDelta": 0}, {"id": "s_mustard", "name": "Mustard", "priceDelta": 0}, {"id": "s_mayo", "name": "Mayo", "priceDelta": 0}, {"id": "s_og", "name": "OG House", "priceDelta": 0}, {"id": "s_jranch", "name": "Jalapeño Ranch", "priceDelta": 0}, {"id": "s_bbq", "name": "BBQ", "priceDelta": 0}]}, {"id": "rm_lone", "name": "Remove", "required": false, "min": 0, "max": 5, "options": [{"id": "r_ls_sauce", "name": "No jalapeño ranch", "priceDelta": 0}, {"id": "r_ls_lettuce", "name": "No lettuce", "priceDelta": 0}, {"id": "r_ls_onions", "name": "No sliced onions", "priceDelta": 0}, {"id": "r_ls_jalapenos", "name": "No jalapeños", "priceDelta": 0}, {"id": "r_ls_cheese", "name": "No American cheese", "priceDelta": 0}]}]'),
  ('bbq_bacon','burgers','BBQ Bacon','BBQ sauce, beef bacon, sliced onions, pickles, American cheese',10,false,true,4,'[{"id": "patty", "name": "Patties", "required": true, "min": 1, "max": 1, "options": [{"id": "p_single", "name": "Single patty", "priceDelta": 0}, {"id": "p_double", "name": "Double patty", "priceDelta": 2}, {"id": "p_triple", "name": "Triple patty", "priceDelta": 4}]}, {"id": "toppings_add", "name": "Add toppings", "required": false, "min": 0, "max": 9, "options": [{"id": "t_lettuce", "name": "Lettuce", "priceDelta": 0}, {"id": "t_pickles", "name": "Pickles", "priceDelta": 0}, {"id": "t_tomatoes", "name": "Tomatoes", "priceDelta": 0}, {"id": "t_cucumbers", "name": "Cucumbers", "priceDelta": 0}, {"id": "t_onions", "name": "Sliced onions", "priceDelta": 0}, {"id": "t_jalapenos", "name": "Jalapeños", "priceDelta": 0}, {"id": "t_egg", "name": "Fried egg", "priceDelta": 1.5}, {"id": "t_avocado", "name": "Avocado", "priceDelta": 1.5}, {"id": "t_bacon", "name": "Beef bacon", "priceDelta": 1.5}]}, {"id": "sauces_add", "name": "Add sauces", "required": false, "min": 0, "max": 6, "options": [{"id": "s_ketchup", "name": "Ketchup", "priceDelta": 0}, {"id": "s_mustard", "name": "Mustard", "priceDelta": 0}, {"id": "s_mayo", "name": "Mayo", "priceDelta": 0}, {"id": "s_og", "name": "OG House", "priceDelta": 0}, {"id": "s_jranch", "name": "Jalapeño Ranch", "priceDelta": 0}, {"id": "s_bbq", "name": "BBQ", "priceDelta": 0}]}, {"id": "rm_bbq", "name": "Remove", "required": false, "min": 0, "max": 5, "options": [{"id": "r_bb_sauce", "name": "No BBQ sauce", "priceDelta": 0}, {"id": "r_bb_bacon", "name": "No beef bacon", "priceDelta": 0}, {"id": "r_bb_onions", "name": "No sliced onions", "priceDelta": 0}, {"id": "r_bb_pickles", "name": "No pickles", "priceDelta": 0}, {"id": "r_bb_cheese", "name": "No American cheese", "priceDelta": 0}]}]'),
  ('build_your_own','burgers','Build Your Own','Start with the patty, add what you want',9,false,true,5,'[{"id": "patty", "name": "Patties", "required": true, "min": 1, "max": 1, "options": [{"id": "p_single", "name": "Single patty", "priceDelta": 0}, {"id": "p_double", "name": "Double patty", "priceDelta": 2}, {"id": "p_triple", "name": "Triple patty", "priceDelta": 4}]}, {"id": "byo_build", "name": "Build it", "required": false, "min": 0, "max": 15, "options": [{"id": "b_cheese", "name": "American cheese", "priceDelta": 0}, {"id": "b_lettuce", "name": "Lettuce", "priceDelta": 0}, {"id": "b_pickles", "name": "Pickles", "priceDelta": 0}, {"id": "b_tomatoes", "name": "Tomatoes", "priceDelta": 0}, {"id": "b_cucumbers", "name": "Cucumbers", "priceDelta": 0}, {"id": "b_onions", "name": "Sliced onions", "priceDelta": 0}, {"id": "b_jalapenos", "name": "Jalapeños", "priceDelta": 0}, {"id": "b_egg", "name": "Fried egg", "priceDelta": 1.5}, {"id": "b_avocado", "name": "Avocado", "priceDelta": 1.5}, {"id": "b_bacon", "name": "Beef bacon", "priceDelta": 1.5}]}, {"id": "sauces_add", "name": "Add sauces", "required": false, "min": 0, "max": 6, "options": [{"id": "s_ketchup", "name": "Ketchup", "priceDelta": 0}, {"id": "s_mustard", "name": "Mustard", "priceDelta": 0}, {"id": "s_mayo", "name": "Mayo", "priceDelta": 0}, {"id": "s_og", "name": "OG House", "priceDelta": 0}, {"id": "s_jranch", "name": "Jalapeño Ranch", "priceDelta": 0}, {"id": "s_bbq", "name": "BBQ", "priceDelta": 0}]}]'),
  ('wings','wings','Wings','Dry rub or wet rub',8,true,true,6,'[{"id": "wing_count", "name": "How many", "required": true, "min": 1, "max": 1, "options": [{"id": "w_4", "name": "4 piece", "priceDelta": 0}, {"id": "w_6", "name": "6 piece", "priceDelta": 3}, {"id": "w_8", "name": "8 piece", "priceDelta": 6}, {"id": "w_10", "name": "10 piece", "priceDelta": 9}]}, {"id": "wing_flavor", "name": "Flavor", "required": true, "min": 1, "max": 1, "options": [{"id": "wf_dry_bbq", "name": "Dry rub — BBQ", "priceDelta": 0}, {"id": "wf_dry_cajun", "name": "Dry rub — Cajun", "priceDelta": 0}, {"id": "wf_dry_texas", "name": "Dry rub — Texas Heat", "priceDelta": 0}, {"id": "wf_dry_lemon", "name": "Dry rub — Lemon Pepper", "priceDelta": 0}, {"id": "wf_dry_garlic", "name": "Dry rub — Garlic Parmesan", "priceDelta": 0}, {"id": "wf_wet_bbq", "name": "Wet rub — BBQ", "priceDelta": 0}, {"id": "wf_wet_og", "name": "Wet rub — OG House", "priceDelta": 0}, {"id": "wf_wet_jranch", "name": "Wet rub — Jalapeño Ranch", "priceDelta": 0}]}]'),
  ('smash_fries','fries','Smash Fries','Seasoned fries, smash patty, choice of sauce & toppings',8,true,true,7,'[{"id": "patty", "name": "Patties", "required": true, "min": 1, "max": 1, "options": [{"id": "p_single", "name": "Single patty", "priceDelta": 0}, {"id": "p_double", "name": "Double patty", "priceDelta": 2}, {"id": "p_triple", "name": "Triple patty", "priceDelta": 4}]}, {"id": "sauce_pick", "name": "Choice of sauce", "required": true, "min": 1, "max": 1, "options": [{"id": "sp_ketchup", "name": "Ketchup", "priceDelta": 0}, {"id": "sp_mustard", "name": "Mustard", "priceDelta": 0}, {"id": "sp_mayo", "name": "Mayo", "priceDelta": 0}, {"id": "sp_og", "name": "OG House", "priceDelta": 0}, {"id": "sp_jranch", "name": "Jalapeño Ranch", "priceDelta": 0}, {"id": "sp_bbq", "name": "BBQ", "priceDelta": 0}]}, {"id": "toppings_add", "name": "Add toppings", "required": false, "min": 0, "max": 9, "options": [{"id": "t_lettuce", "name": "Lettuce", "priceDelta": 0}, {"id": "t_pickles", "name": "Pickles", "priceDelta": 0}, {"id": "t_tomatoes", "name": "Tomatoes", "priceDelta": 0}, {"id": "t_cucumbers", "name": "Cucumbers", "priceDelta": 0}, {"id": "t_onions", "name": "Sliced onions", "priceDelta": 0}, {"id": "t_jalapenos", "name": "Jalapeños", "priceDelta": 0}, {"id": "t_egg", "name": "Fried egg", "priceDelta": 1.5}, {"id": "t_avocado", "name": "Avocado", "priceDelta": 1.5}, {"id": "t_bacon", "name": "Beef bacon", "priceDelta": 1.5}]}]'),
  ('seasoned_fries','fries','Seasoned Fries','House seasoned fries',5,false,true,8,'[]'),
  ('can_drink','beverages','Can Drink','',2,false,true,9,'[{"id": "drink_pick", "name": "Which one", "required": true, "min": 1, "max": 1, "options": [{"id": "d_coke", "name": "Coke", "priceDelta": 0}, {"id": "d_diet", "name": "Diet Coke", "priceDelta": 0}, {"id": "d_sprite", "name": "Sprite", "priceDelta": 0}, {"id": "d_fanta", "name": "Fanta", "priceDelta": 0}, {"id": "d_drpepper", "name": "Dr Pepper", "priceDelta": 0}]}]'),
  ('water','beverages','Water','',1.5,false,true,10,'[]');

insert into rewards (id, name, points_cost, menu_item_id) values
  ('rw_drink','Free Can Drink',200,'can_drink'),
  ('rw_sfries','Free Seasoned Fries',500,'seasoned_fries'),
  ('rw_wings','Free Wings',800,'wings'),
  ('rw_og','Free The OG',900,'og');

update truck_status set is_open = false, halal = true,
  location_name = 'TBD', address = 'Houston, TX',
  hours_text = 'TBD', prep_minutes = 15,
  instagram = 'https://www.instagram.com/buns.patties' where id = 1;
