// Writes supabase/seed.sql from data/menu.seed.json, so the database and the
// demo app can never disagree about the menu. Run after editing the menu:
//   node scripts/build-seed.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const seed = JSON.parse(readFileSync(new URL('../data/menu.seed.json', import.meta.url)));
const q = (s) => (s === null || s === undefined ? 'null' : `'${String(s).replace(/'/g, "''")}'`);
const j = (v) => `${q(JSON.stringify(v))}::jsonb`;

const cats = seed.categories.map((c) => `  (${q(c.id)},${q(c.name)},${c.sort})`).join(',\n');
const items = seed.items.map((i, n) => {
  const groups = i.modifierGroups.map((g) => seed.modifierGroups[g]);
  return `  (${q(i.id)},${q(i.categoryId)},${q(i.name)},${q(i.description)},${i.price},${!!i.featured},${i.available !== false},${n + 1},${j(groups)},${j(i.includes ?? [])},${j(i.defaults ?? {})})`;
}).join(',\n');
const t = seed.truck;

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), `-- Buns & Patties real menu. Run after schema.sql.
-- GENERATED by scripts/build-seed.mjs from data/menu.seed.json — edit that, not this.
delete from order_lines; delete from menu_items; delete from categories;

insert into categories (id, name, sort) values
${cats};

insert into menu_items (id, category_id, name, description, price, featured, available, sort, modifier_groups, includes, defaults) values
${items};

update truck_status set is_open = false, halal = ${!!t.halal},
  location_name = ${q(t.locationName)}, address = ${q(t.address)},
  hours_text = ${q(t.hoursText)}, prep_minutes = ${t.prepMinutes},
  instagram = ${q(t.instagram)} where id = 1;
`);
console.log('wrote supabase/seed.sql:', seed.items.length, 'items');
